/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  wranglesXLSidebar: [
    {type: 'doc', id: 'account', label: 'Account'},
    {type: 'doc', id: 'organizations', label: 'Organizations'},
    {type: 'doc', id: 'excel', label: 'Basics and Terminology'},
    {type: 'doc', id: 'excel/install', label: 'Install'},
    {type: 'doc', id: 'excel/stock', label: 'Stock Wrangles'},
    {type: 'doc', id: 'excel/my_wrangles', label: 'My Wrangles'},
    {type: 'doc', id: 'excel/recipes', label: 'Recipes'},
    {
      type: 'category',
      label: 'Tutorials',
      link: {type: 'doc', id: "excel/Let's-Get-Ready-To-Wrangle"},
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: "excel/Let's-Get-Ready-To-Wrangle",
        },
      ],
    },
    {type: 'doc', id: 'excel/releases', label: 'Releases'},
    {type: 'doc', id: 'python', label: 'Python'},
    {type: 'doc', id: 'python/install', label: 'Python Install'},
    {
      type: 'category',
      label: 'Python Recipes',
      link: {type: 'doc', id: 'python/recipes'},
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'python/recipes'}],
    },
    {type: 'doc', id: 'python/functions', label: 'Python Functions'},
  ],

  wranglesPYConnectorsSidebar: [
    {type: 'link', label: 'Registry', href: '/wrangles'},
    {
      type: 'category',
      label: 'Connectors',
      link: {type: 'doc', id: 'python/connectors'},
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'python/connectors'}],
    },
  ],
};

export default sidebars;
