const assert = require('node:assert/strict');
const path = require('node:path');
const test = require('node:test');

const {
  generateRegistryCatalog,
  renderRegistryCatalog,
} = require('./generate-playground-registry.cjs');

const SITE_ROOT = path.resolve(__dirname, '..');
const MANIFEST_PATH = path.join(SITE_ROOT, 'static', 'registry', 'manifest.json');

test('generates every Playground entry from the compiled Registry', () => {
  const result = generateRegistryCatalog(MANIFEST_PATH);

  assert.equal(result.registryVersion, '0.3.0');
  assert.equal(result.contractVersion, '0.3');
  assert.equal(result.catalog.length, 98);
  assert.equal(new Set(result.catalog.map((entry) => entry.catalogId)).size, 98);
  assert.equal(new Set(result.catalog.map((entry) => entry.catalogKey)).size, 98);
  assert.equal(new Set(result.catalog.map((entry) => entry.type)).size, 98);
  assert.ok(result.catalog.every((entry) => entry.registryRoute.startsWith('/wrangles/')));
});

test('uses contract identity, parameters, defaults, and Recipe Writer eligibility', () => {
  const {catalog} = generateRegistryCatalog(MANIFEST_PATH);
  const convertCase = catalog.find((entry) => entry.type === 'convert.case');

  assert.deepEqual(
    {
      catalogId: convertCase.catalogId,
      catalogKey: convertCase.catalogKey,
      eligible: convertCase.recipeWriterEligible,
      category: convertCase.category,
      route: convertCase.registryRoute,
    },
    {
      catalogId: '5',
      catalogKey: 'convert.case',
      eligible: true,
      category: 'Convert',
      route: '/wrangles/namespaces/convert#case',
    },
  );
  assert.equal(convertCase.defaults.case, 'lower');
  assert.equal(convertCase.fields.find((field) => field.key === 'case').type, 'select');
  assert.deepEqual(
    convertCase.fields.find((field) => field.key === 'case').options.map((option) => option.value),
    ['lower', 'upper', 'title', 'sentence'],
  );
  assert.ok(!convertCase.fields.some((field) => ['if', 'where', 'where_params'].includes(field.key)));
});

test('renders a deterministic generated module with Registry provenance', () => {
  const result = generateRegistryCatalog(MANIFEST_PATH);
  const rendered = renderRegistryCatalog(result, 'static/registry/manifest.json');

  assert.match(rendered, /generated by scripts\/generate-playground-registry\.cjs/);
  assert.match(rendered, /PLAYGROUND_REGISTRY_VERSION = "0\.3\.0"/);
  assert.match(rendered, /"catalogKey": "convert\.case"/);
  assert.match(rendered, /"catalogId": "5"/);
});
